#!/bin/bash

echo "🔧 Setting up Supabase database for BOL Seller Messenger v3"
echo ""
echo "📋 Instructions:"
echo "1. Go to https://yevbyifrvawltdcxfrvx.supabase.co"
echo "2. Navigate to SQL Editor"
echo "3. Create a new query"
echo "4. Copy and paste the contents of supabase-schema.sql"
echo "5. Run the query"
echo ""
echo "Or use Supabase CLI:"
echo "  supabase db push"
echo ""
echo "📝 Schema file: supabase-schema.sql"
echo ""
echo "After running the schema, add these environment variables to Vercel:"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL=https://yevbyifrvawltdcxfrvx.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=<get from Supabase Settings → API>"
echo ""
